INSERT INTO museum_entity (id, name, description, address, city, image, founded_before) VALUES
('1', 'Museo del Oro', 'Colección única de orfebrería precolombina', 'Cra 6 #15-88', 'Bogota', 'https://example.com/images/oro.jpg', 1939),
('2', 'Museo Nacional de Colombia', 'Sala dedicada a la historia y el arte nacional', 'Cra 7 #28-66', 'Bogota', 'https://example.com/images/nacional.jpg', 1823),
('3', 'Museo de Antioquia', 'Colección permanente de arte moderno', 'Cra 52 #52-43', 'Medellin', 'https://example.com/images/antioquia.jpg', 1881),
('4', 'Museo Botero', 'Obras donadas por Fernando Botero', 'Calle 11 #4-41', 'Bogota', 'https://example.com/images/botero.jpg', 2000),
('5', 'Museo del Caribe', 'Relatos de la cultura caribeña', 'Calle 36 #46-66', 'Barranquilla', 'https://example.com/images/caribe.jpg', 2008),
('6', 'Museo Taminango', 'Artesanías tradicionales de Nariño', 'Carrera 28 #5-56', 'Pasto', 'https://example.com/images/taminango.jpg', 1971),
('7', 'Museo Quimbaya', 'Patrimonio arqueológico del Eje Cafetero', 'Av. Bolívar #40N-80', 'Armenia', 'https://example.com/images/quimbaya.jpg', 1986),
('8', 'Museo La Tertulia', 'Arte moderno latinoamericano', 'Av. Colombia #5-105', 'Cali', 'https://example.com/images/tertulia.jpg', 1968),
('9', 'Museo del Vidrio', 'Oficios tradicionales de vidrio soplado', 'Calle 37 sur #24B-91', 'Bogota', 'https://example.com/images/vidrio.jpg', 2000),
('10', 'Museo del Rio Magdalena', 'Narraciones sobre el gran rio', 'Malecón Turístico', 'Honda', 'https://example.com/images/magdalena.jpg', 2013),
('11', 'Museo Naval del Caribe', 'Historia naval y militar', 'Calle San Juan de Dios', 'Cartagena', 'https://example.com/images/naval.jpg', 1992),
('12', 'Museo del Agua', 'Experiencias interactivas alrededor del agua', 'Calle 24 #5-63', 'Bogota', 'https://example.com/images/agua.jpg', 2012),
('13', 'Museo Rayo', 'Arte contemporáneo latinoamericano', 'Calle 5 #8-36', 'Roldanillo', 'https://example.com/images/rayo.jpg', 1981),
('14', 'Museo de Arte Religioso', 'Patrimonio religioso colonial', 'Cra 4 #36-56', 'Popayan', 'https://example.com/images/religioso.jpg', 1765),
('15', 'Museo del Caribe Tayrona', 'Memoria ancestral de la Sierra Nevada', 'Parque Cultural Tayrona', 'Santa Marta', 'https://example.com/images/tayrona.jpg', 2015),
('16', 'Museo de Arte Moderno de Medellin', 'Escenarios de arte contemporáneo', 'Carrera 44 #19A-100', 'Medellin', 'https://example.com/images/mamm.jpg', 2009),
('17', 'Museo Arqueologico Casa del Marques', 'Colección de piezas coloniales', 'Carrera 2 #1-37', 'Villa de Leyva', 'https://example.com/images/marques.jpg', 1969),
('18', 'Museo Maloka', 'Ciencia interactiva para todas las edades', 'Cra 68D #24A-51', 'Bogota', 'https://example.com/images/maloka.jpg', 1998),
('19', 'Museo del Carnaval', 'Antecedentes de la fiesta barranquillera', 'Carrera 54 #49B-39', 'Barranquilla', 'https://example.com/images/carnaval.jpg', 2011),
('20', 'Museo de la Independencia', 'Casa histórica del Florero', 'Carrera 7 #11-28', 'Bogota', 'https://example.com/images/independencia.jpg', 1810),
('21', 'Museo El Chicó', 'Colección de arte decorativo', 'Cra 7 #93-01', 'Bogota', 'https://example.com/images/chico.jpg', 1964);